"""initial fastapi app"""
from pathlib import Path

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi
from fastapi.routing import APIRoute

from app.api.routes.api import router as api_router
from app.custom_logging import CustomizeLogger
from app.db.events import init_db
from app.error_handler import add_chatbot_exception_handler

tags_metadata = [
    {"name": "Chatbot", "description": "chatbot管理相關功能"},
    {"name": "ModelManager", "description": "訓練及管理模型的相關功能"},
    {"name": "SLU", "description": "slu相關功能"},
    {"name": "Template", "description": "template功能"},
    {"name": "Retrieval", "description": "Retrieval相關功能"},
]


config_path = Path(__file__).parent.joinpath("core/logging_config.json")


def create_app() -> FastAPI:
    app = FastAPI(title="Chatbot API", debug=False, openapi_tags=tags_metadata)
    logger = CustomizeLogger.make_logger(config_path)
    app.logger = logger

    return app


app = create_app()

add_chatbot_exception_handler(app)


@app.on_event("startup")
async def startup():
    """connect db"""
    init_db()


app.include_router(api_router)


def use_route_names_as_operation_ids(app: FastAPI) -> None:
    for route in app.routes:
        if isinstance(route, APIRoute):
            route.operation_id = route.name.replace("_", " ").capitalize()


use_route_names_as_operation_ids(app)


def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = get_openapi(title="Chatbot API", version="0.3.1", routes=app.routes)

    # modify autogenerated schema name
    openapi_schema["components"]["schemas"]["ImportInput"] = openapi_schema["components"][
        "schemas"
    ].pop("Body_import_model_chatbots__chatbot_pk__models_import_post")
    openapi_schema["components"]["schemas"]["ImportInput"]["title"] = "ImportInput"
    openapi_schema["paths"]["/chatbots/{chatbot_pk}/models/import"]["post"]["requestBody"][
        "content"
    ]["multipart/form-data"]["schema"]["$ref"] = "#/components/schemas/ImportInput"

    openapi_schema["components"]["schemas"]["RetrievalDatasetInput"] = openapi_schema["components"][
        "schemas"
    ].pop("Body_create_retrieval_dataset_chatbots__chatbots_id__retrieval_datasets_post")
    openapi_schema["components"]["schemas"]["RetrievalDatasetInput"][
        "title"
    ] = "RetrievalDatasetInput"
    openapi_schema["paths"]["/chatbots/{chatbots_id}/retrieval/datasets"]["post"]["requestBody"][
        "content"
    ]["multipart/form-data"]["schema"]["$ref"] = "#/components/schemas/RetrievalDatasetInput"

    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = custom_openapi
